* Confluence to ElasticSearch

A collection of business processes used to mine Confluence, discover information, intelligently index it and expose all of it as a lightning fast search.

*** Prerequisites

- Git (of course).
- JRE 8 must exist in PATH (JRE 7 is fine too, but might be deprecated).
- Boot 2.x: installation instructions are avaliable [[https://github.com/boot-clj/boot#install][here]].

*** Configuration

search profiles are prod level

*** Usage

After making sure that software from Prerequisites is installed, clone this repo and bring up REPL with ~boot repl~ command (it might take a few minutes to download all dependencies when run for the first time).

Examples:
#+BEGIN_EXAMPLE
./data-miner -a reinit -c context-demo-twiki -d elasticsearch-prod
./data-miner -a scan -c context-demo-twiki -d elasticsearch-prod -s twiki-demo-prod
./data-miner -a scan -c context-demo-confluence -d confluence-demo-cache -s confluence-demo-prod
./data-miner -a scan -c context-demo-confluence -d elasticsearch-prod -s confluence-demo-cache

./data-miner -a scan -c context-demo-twiki -d datahub-prod -s twiki-demo-prod
./data-miner -a scan -c context-demo-confluence -d datahub-prod -s confluence-demo-prod

./data-miner -a update -c context-demo-confluence -d datahub-prod -s confluence-demo-prod

./data-miner -a update -c context-hbase -d elasticsearch-prod
./data-miner -a update -c context-hbase

#+END_EXAMPLE

Once above is completed (should take a few minutes), a subdirectory ~db~ is created. It contains both copy of Confluence and other data sources.
